### ISSUE TITLE
encodeArray.vi repeats the first element

### ISSUE THREAD

**Issue by zoyo-de** [mradziwo/MsgPack_LabVIEW#1]
Hi,
arrays are encoded wrong. Only the first element of the input-array gets encoded to msgpack and repeated for all elements in the output-array. In the first loop of encodeArray.vi the Index(1D)-input should eventually be connected to the i-terminal of the loop. 

regards,
Zoyo

**Comment by PronovaPaul** [comment]
I've corrected this in the refactored version.

**Comment by zoyo-de** [comment]
Oh, this was already fixed in the merged version.
