### ISSUE TITLE
decoding of positive fixint mixed with int

### ISSUE THREAD

**Issue by zoyo-de** [mradziwo/MsgPack_LabVIEW#3]
Hi,
I just see that decodeObject.vi calls for values of  0..127 decodeInt.vi. This has a case for these values, which are positive fixint, but convert it to i8. I would expect that decodeObject.vi should call decodeUInt.vi which implements this case and converts it to the correct u8.  Maybe I missed something but this looks odd.

kind regards,
Christian

**Comment by mradziwo** [comment]
I have copied this behavior from one of the C implementations.  It treats any value from -128 to 127 as  i8. 
I agree it may seem counter intuitive to convert 0-127 to i8, but on the other hand it's consistent with -128-0 range and in case of  LabVIEW implementation has no impact if one oulr like to cast 0-127 as u8.

**Comment by zoyo-de** [comment]
Yes, it's just an unexpected type conversion.
