### ISSUE TITLE
Labview 2015 Version

### ISSUE THREAD

**Issue by PronovaPaul** [mradziwo/MsgPack_LabVIEW#4]
Hey Mike,

Is there a way that you could save this project as a Labview 2015 VIs?  I can't currently open any of the items.

Thanks,
-Paul

**Comment by mradziwo** [comment]
should be doable ;)
I will have access to source tomorrow afternoon and I'll try to make it for
you.


Best regards,
Michał Radziwon

**Comment by PronovaPaul** [comment]
Hey Michał,

I refactored the Encode side of things to get rid of the OpenG libraries, and much of the redundant variant checks.  I ran a few bench tests and I have the encode speed much faster.  Depending on the data (if there are large arrays of float/doubles), it even beats the NI JSON encoder.  I have a test project that compares the following serializers: NI JSON encoder, JKI JSON encoder, MsgPack_Labview (as pulled from this repository), MsgPack_Labview (as refactored by me), and a Msgpack_Labview (using C-libraries: https://sourceforge.net/p/msgpack-labview/wiki/Home/)

Do you want me to branch the code and upload what I have done? 

Here's a screen shot of the speed test VI:  "Speed" and "Compression" is serializer reference to JSON encoder.  Lower numbers are better.

![messagepack speed test](https://user-images.githubusercontent.com/40801983/50030657-854db200-ffc2-11e8-8ea9-b7ef655fafb1.jpg)
